version: '3'

services:

        jenkins:

                image: jenkins

                container_name: jenkins

                ports:

                        - "8080:8080"

                        - "50000:50000"

                restart: always

                volumes:

                        - ./FOR_JENKINS:/var/jenkins_home

        artifactory:

                image: docker.bintray.io/jfrog/artifactory-oss:5.5.1

                container_name: artifactory

                ports:

                        - 8081:8081

                volumes:

                        - /data/artifactory:/var/opt/jfrog/artifactory

                #    Add extra Java options by uncommenting the following lines

                #    environment:

                #     - EXTRA_JAVA_OPTIONS=-Xmx4g

                restart: always

                ulimits:

                        nproc: 65535

                        nofile:

                                soft: 32000

                                hard: 40000